version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "16.15.1"
      - checkout
      - aws-cli/setup
      - eb/setup
      # install dependencies in both apps
      - run:
          name: Installing Backend
          command: |
            npm run backend:install
      - run:
          name: Installing Frontend
          command: |
            npm run frontend:install
      # build front-end and backend
      - run:
          name: Building Backend
          command: |
            npm run backend:build
      - run:
          name: Building Frontend
          command: |
            npm run frontend:build
      # deploy front-end and backend 
      # - run:
      #     name: Deploying Backend
      #     command: |
      #       npm run backend:deploy
      - run:
          name: Deploying Frontend
          command: |
            npm run frontend:deploy
# workflows:
#   Udagram:
#     jobs:
#       - test
#       - build
#       - hold:
#           filters:
#             branches:
#               only:
#                 - main
#           type: approval
#       - deploy:
#           requires:
#             - hold